env:
  global:
  - FREECAD_RELEASE="0.18"
  - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
  - DEPLOY_REPO=${DEPLOY_REPO:-xform3/FreeCAD-AppImg}
  - DEPLOY="1"
os: linux
compiler: gcc
language: cpp
before_install:
- sudo apt-get update -qq && sudo apt-get install -y desktop-file-utils jq zsync
- curl -LO "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
- chmod +x jq-linux64 && sudo mv jq-linux64 $(which jq)
install:
- curl -LO https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage
- wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
- chmod a+x appimagetool-x86_64.AppImage
- wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
script:
- bash -ex ./pkg2appimage FreeCAD-Daily
- out/*.AppImage --console $TRAVIS_BUILD_DIR/out/version.py
- cd out
- FC_VERSION=$(ls *.AppImage)
- rm *.AppImage
- |
  ARCH=x86_64 $TRAVIS_BUILD_DIR/appimagetool-x86_64.AppImage \
  -u "gh-releases-zsync|FreeCAD|FreeCAD|0.18_pre|FreeCAD*glibc2.17-x86_64.AppImage.zsync" \
  $TRAVIS_BUILD_DIR/FreeCAD-Daily/FreeCAD-Daily.AppDir \
  $TRAVIS_BUILD_DIR/out/$FC_VERSION
- cd ..
- cd conda
- bash ./conda.sh
- cd ..
after_success:
- mkdir images
- cp out/*.AppImage images/
- cp conda/*AppImage images/
- ls -lh images/* # Assuming you have some files in out/ that you would like to upload
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- bash upload.sh images/*

deploy:
  provider: gcs
  access_key_id: $GCS_KEY_ID
  secret_access_key: $GCS_ACCESS_KEY
  bucket: gen-content
  local-dir: images
  skip_cleanup: true